[versions]
spring = "6.2.7"
jakarta-annotation = "3.0.0"
jakarta-persistence = "3.1.0"
postgres = "42.7.5"
hikaricp = "6.3.0"
aspectj = "1.9.24"
slf4j = "2.0.17"
logback = "1.5.18"
hibernate = "7.0.0.Final"
ehcache = "3.10.8"


[libraries]
spring-context = { module = "org.springframework:spring-context", version.ref = "spring" }
spring-aop = { module = "org.springframework:spring-aop", version.ref = "spring" }
jakarta-annotation = { module = "jakarta.annotation:jakarta.annotation-api", version.ref = "jakarta-annotation"}
postgres = { module = "org.postgresql:postgresql", version.ref = "postgres" }
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }
aspectjweaver = { module = "org.aspectj:aspectjweaver", version.ref = "aspectj" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
hibernate-core = { module = "org.hibernate.orm:hibernate-core", version.ref = "hibernate"}
hibernate-jcache = { module = "org.hibernate.orm:hibernate-jcache", version.ref = "hibernate"}
jakarta-persistence = { module = "jakarta.persistence:jakarta.persistence-api", version.ref = "jakarta-persistence" }
spring-orm = { module = "org.springframework:spring-orm", version.ref = "spring" }
ehcache = { module = "org.ehcache:ehcache", version.ref = "ehcache" }

[bundles]
spring = ["spring-context", "spring-aop", "spring-orm", "jakarta-annotation"]
database = ["postgres", "hikaricp", "hibernate-core", "hibernate-jcache", "jakarta-persistence", "ehcache"]
logging = ["slf4j-api", "logback-classic"]