[versions]
spring = "6.2.5"
jackson = "2.18.3"
aspectj = "1.9.23"
slf4j = "2.0.17"
logback = "1.5.18"

[libraries]
spring-context = { module = "org.springframework:spring-context", version.ref = "spring" }
spring-aop = { module = "org.springframework:spring-aop", version.ref = "spring" }
aspectjweaver = { module = "org.aspectj:aspectjweaver", version.ref = "aspectj" }
jackson-csv = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-csv", version.ref = "jackson" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

[bundles]
spring = ["spring-context", "spring-aop"]
logging = ["slf4j-api", "logback-classic"]